apiVersion: apps/v1
kind: Deployment
metadata:
  name: codesync-backend
  labels:
    app: codesync-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codesync-backend
  template:
    metadata:
      labels:
        app: codesync-backend
    spec:
      containers:
      - name: codesync-backend
        image: __SERVER_IMAGE__           # e.g. docker.io/youruser/codesync-server:123
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: codesync-server-secrets   # all server secrets injected as env vars
        - configMapRef:
            name: codesync-config           # non-sensitive config
        readinessProbe:
          httpGet:
            path: /healthz   # or your server health endpoint
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
