apiVersion: v1
kind: Service
metadata:
  name: codesync-frontend
  labels:
    app: codesync-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: codesync-frontend
