apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: three-tier
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb   # <-- MongoDB storage directory
