apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: three-tier
type: Opaque
data:
  username: Z2l0YXVzZXI=  # base64("mongouser")
  password: N1BIWXh4UFBCTndHNzZMcg==  # base64("mongopass")
