apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: three-tier
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9naXRhdXNlcjo3UEhZeHhQUEJOd0c3NkxyQGNsdXN0ZXIwLjU5dHB4ZmQubW9uZ29kYi5uZXQvQ29kZVN5bmM/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  FRONTEND_URL: aHR0cHM6Ly9zeW5jdG9nZXRoZXIubmV0bGlmeS5hcHA=
  GITHUB_CALLBACK_URL: aHR0cHM6Ly9jb2RlLXN5bmMtbWFpbi0xdnIwLm9ucmVuZGVyLmNvbS9hcGkvYXV0aC9naXRodWIvY2FsbGJhY2s=
  GITHUB_CLIENT_ID: T3YyM2xpRWxtSVZVSEpTQm9QeFQ=
  GITHUB_CLIENT_SECRET: N2VmZTA0OGJhYjk5ZWM4MTIyYmJiNTYzOTllZTg2YzJlMjVjYjkxYg==
  JWT_SECRET: Y29kZV9zeW5jOTA4Mzc4Mg==
  SESSION_SECRET: bHo2ZGlNRFdIU1pKd0thV2dDSEtJalRyQXdZMTZLM1puYkZUNTY4SjdvMD0=
  NODE_ENV: cHJvZHVjdGlvbg==
  PORT: ODAwMA==